import type { ActivityItem, CampaignResults, Candidate, Collaboration, CreatorProfile, DemoState, MemorySignal, RankedCandidate } from "./types";

export const STORAGE_KEY = "collabmind-demo-v2";
export const DEFAULT_PROFILE: CreatorProfile = { name:"Maya", niche:"Cybersecurity", platform:"YouTube", followers:32000, audienceGoal:"Web developers", avoid:"Crypto, gambling and unrelated sponsorships", tone:"Technical, practical and educational", formats:["Challenge video","Technical teardown","Joint build"] };
export const EMPTY_STATE: DemoState = { profile:null, memories:[], rejectedCreatorIds:[], collaborations:[], activity:[] };

export const CANDIDATES: Candidate[] = [
  { id:"alex-chen", name:"Alex Chen", handle:"@alexbuilds", initials:"AC", role:"Frontend engineer & educator", niche:"Web Development", platform:"YouTube", followers:184000, location:"Toronto", baseScore:91, responseRate:87, audience:["web developers","frontend engineers","indie hackers"], tags:["technical","developer","engineering","react"], formats:["Challenge video","Joint build","Technical teardown"], color:"#5470c6", bio:"Builds production web apps in public and teaches the decisions behind them.", concept:"I hired a hacker to break my React app", why:"His developer-heavy audience is exactly where Maya wants to grow, while Maya adds a clear security angle Alex does not cover alone.", risk:"Keep the exploit educational and use a sandboxed demo application." },
  { id:"priya-nair", name:"Priya Nair", handle:"@shipwithpriya", initials:"PN", role:"Full-stack product builder", niche:"Developer Tools", platform:"YouTube", followers:97000, location:"Bengaluru", baseScore:88, responseRate:91, audience:["web developers","startup engineers","product builders"], tags:["technical","developer","saas","engineering"], formats:["Joint build","Technical teardown","Live workshop"], color:"#9d6b53", bio:"Ships useful developer tools and narrates the product and engineering trade-offs.", concept:"Build a secure micro-SaaS in one afternoon", why:"Priya brings a practical building audience and a credible format for showing security as part of shipping—not an afterthought.", risk:"Scope the build to one feature so the story stays clear." },
  { id:"marcus-lee", name:"Marcus Lee", handle:"@cloudwithmarcus", initials:"ML", role:"Cloud security architect", niche:"Cloud Engineering", platform:"LinkedIn", followers:68000, location:"Singapore", baseScore:84, responseRate:74, audience:["backend developers","cloud engineers","security teams"], tags:["technical","cloud","security","enterprise"], formats:["Technical teardown","Live workshop","Expert interview"], color:"#477a70", bio:"Makes cloud infrastructure and application security legible to working teams.", concept:"We hardened a startup stack before launch day", why:"Marcus adds enterprise credibility and shares Maya's technical depth, with enough audience adjacency to unlock new reach.", risk:"The overlap is strong, so assign distinct roles to avoid repeating the same advice." },
  { id:"lena-ortiz", name:"Lena Ortiz", handle:"@designsystems", initials:"LO", role:"Design systems lead", niche:"Product Design", platform:"YouTube", followers:142000, location:"Madrid", baseScore:79, responseRate:83, audience:["product designers","frontend engineers","design engineers"], tags:["design","developer","accessibility","product"], formats:["Joint build","Design critique","Technical teardown"], color:"#8a5f79", bio:"Explores the craft and implementation details behind resilient product interfaces.", concept:"Designing a login flow attackers cannot exploit", why:"Lena introduces a design-engineering audience and turns security into a visible product-quality story.", risk:"Frame the topic around user trust so it remains relevant to both audiences." },
  { id:"noah-williams", name:"Noah Williams", handle:"@growthnotes", initials:"NW", role:"Creator growth strategist", niche:"Creator Business", platform:"Instagram", followers:221000, location:"London", baseScore:76, responseRate:93, audience:["creators","marketers","founders"], tags:["business","marketing","creator","growth"], formats:["Expert interview","Case study","Carousel"], color:"#8c784c", bio:"Breaks down creator growth systems, sponsorships and content operations.", concept:"The security mistakes quietly killing creator businesses", why:"Noah offers broad distribution, but his audience is less technical than Maya's stated growth target.", risk:"The business framing may feel too broad for Maya's core audience." },
  { id:"sara-kim", name:"Sara Kim", handle:"@aiforsolo", initials:"SK", role:"AI workflow creator", niche:"AI Productivity", platform:"TikTok", followers:310000, location:"Seoul", baseScore:73, responseRate:89, audience:["creators","marketers","solo founders"], tags:["ai","business","marketing","productivity"], formats:["Challenge video","Short series","Tool review"], color:"#6c648d", bio:"Tests practical AI workflows for solo operators and creator-led businesses.", concept:"Can an AI assistant pass a security review?", why:"The challenge format is promising, though the audience match is broader than Maya's developer goal.", risk:"Avoid generic AI claims; ground the collaboration in a real threat model." },
  { id:"diego-ramos", name:"Diego Ramos", handle:"@mobiledecoded", initials:"DR", role:"Mobile app engineer", niche:"Mobile Development", platform:"YouTube", followers:119000, location:"Mexico City", baseScore:82, responseRate:79, audience:["mobile developers","web developers","engineering students"], tags:["technical","developer","mobile","engineering"], formats:["Challenge video","Joint build","Code review"], color:"#627b52", bio:"Builds polished mobile products and shares the engineering process without shortcuts.", concept:"We tried to secure an app before the timer ran out", why:"Diego's engineering audience is adjacent to Maya's target and responds well to high-stakes build challenges.", risk:"Clarify which mobile security ideas transfer to web developers." },
  { id:"amina-yusuf", name:"Amina Yusuf", handle:"@datawithamina", initials:"AY", role:"Data engineering educator", niche:"Data Engineering", platform:"YouTube", followers:86000, location:"Nairobi", baseScore:80, responseRate:76, audience:["data engineers","backend developers","engineering students"], tags:["technical","developer","data","engineering"], formats:["Technical teardown","Joint build","Expert interview"], color:"#8c6250", bio:"Makes data pipelines, privacy and platform engineering approachable without diluting the technical detail.", concept:"What your analytics pipeline exposes about users", why:"Amina creates a strong security-and-data crossover with an audience of working engineers.", risk:"Keep the story concrete with one sample data pipeline." },
];

const makeId = (prefix:string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,6)}`;
const time = () => new Date().toLocaleTimeString([], { hour:"2-digit", minute:"2-digit" });

export function profileMemories(profile:CreatorProfile):MemorySignal[] {
  const stamp = new Date().toISOString();
  return [
    { id:"profile-niche", kind:"profile", title:"Creator identity", detail:`${profile.niche} creator on ${profile.platform}.`, tags:[profile.niche.toLowerCase()], weight:2, source:"onboarding", createdAt:stamp },
    { id:"profile-goal", kind:"goal", title:"Audience goal", detail:`Grow into ${profile.audienceGoal}.`, tags:profile.audienceGoal.toLowerCase().split(/\s+/), weight:3, source:"onboarding", createdAt:stamp },
    { id:"profile-tone", kind:"preference", title:"Creative voice", detail:profile.tone, tags:["technical","educational"], weight:2, source:"onboarding", createdAt:stamp },
    { id:"profile-formats", kind:"preference", title:"Preferred formats", detail:profile.formats.join(", "), tags:profile.formats.map(f=>f.toLowerCase()), weight:2, source:"onboarding", createdAt:stamp },
    { id:"profile-boundary", kind:"boundary", title:"Brand boundary", detail:`Avoid ${profile.avoid}.`, tags:profile.avoid.toLowerCase().split(/[, ]+/).filter(tag=>tag.length>4), weight:-3, source:"onboarding", createdAt:stamp },
  ];
}

export function rankCandidates(profile:CreatorProfile, memories:MemorySignal[], rejectedIds:string[]):RankedCandidate[] {
  const target = profile.audienceGoal.toLowerCase();
  const preferenceText = memories.filter(m=>m.kind==="preference"||m.kind==="outcome").map(m=>`${m.detail} ${m.tags.join(" ")}`).join(" ").toLowerCase();
  const boundaryText = memories.filter(m=>m.kind==="boundary").map(m=>`${m.detail} ${m.tags.join(" ")}`).join(" ").toLowerCase();
  const outcomeTags = memories.filter(m=>m.kind==="outcome").flatMap(m=>m.tags);
  return CANDIDATES.filter(c=>!rejectedIds.includes(c.id)).map(candidate=>{
    let score=candidate.baseScore; const reasons:string[]=[];
    if(candidate.audience.some(a=>target.includes(a)||a.includes(target))){ score+=5; reasons.push(`Direct access to ${profile.audienceGoal.toLowerCase()}`); }
    else if(candidate.audience.some(a=>a.includes("developer"))){ score+=2; reasons.push("Adjacent developer audience"); }
    const format=candidate.formats.find(item=>profile.formats.includes(item))??candidate.formats[0];
    if(profile.formats.includes(format)){ score+=2; reasons.push(`${format} fits your format preference`); }
    const technicalBoundary=boundaryText.includes("technical")||boundaryText.includes("business")||boundaryText.includes("marketing");
    const isBroadBusiness=candidate.tags.some(tag=>tag==="business"||tag==="marketing");
    if(technicalBoundary&&isBroadBusiness){ score-=18; reasons.unshift("Reduced by your non-technical boundary"); }
    if(preferenceText.includes("technical")&&candidate.tags.includes("technical")){ score+=4; reasons.push("Matches your technical depth preference"); }
    if(outcomeTags.includes("challenge")&&candidate.formats.includes("Challenge video")){ score+=6; if(isBroadBusiness)reasons.push("Boosted by your challenge-video result");else reasons.unshift("Boosted by your challenge-video result"); }
    if(outcomeTags.includes("developer")&&candidate.tags.includes("developer")) score+=3;
    score=Math.max(42,Math.min(99,score));
    return {...candidate,score,delta:score-candidate.baseScore,reasons:reasons.slice(0,3),format};
  }).sort((a,b)=>b.score-a.score);
}

export function rejectionMemory(candidate:Candidate, reason:string):MemorySignal { const normalized=reason.toLowerCase(); const tags=[...candidate.tags]; if(normalized.includes("business"))tags.push("business"); if(normalized.includes("marketing"))tags.push("marketing"); if(normalized.includes("technical"))tags.push("technical"); return { id:makeId("rejection"), kind:"boundary", title:"Learned from a rejection", detail:reason, tags:Array.from(new Set(tags)), weight:-4, source:"rejection", createdAt:new Date().toISOString() }; }
export function outcomeMemory(collaboration:Collaboration, results:CampaignResults):MemorySignal { return { id:makeId("outcome"), kind:"outcome", title:"Learned from campaign performance", detail:`${collaboration.format} reached ${results.nonFollowerReach}% non-followers, generated ${results.followersGained.toLocaleString()} followers and ${results.engagement}% engagement.`, tags:[collaboration.format.toLowerCase().includes("challenge")?"challenge":collaboration.format.toLowerCase(),"developer","high-performing"], weight:5, source:"campaign", createdAt:new Date().toISOString() }; }
export function createCollaboration(candidate:RankedCandidate, profile:CreatorProfile):Collaboration { return { id:makeId("collaboration"), creatorId:candidate.id, status:"draft", concept:candidate.concept, format:candidate.format, subject:`Collaboration idea: ${candidate.concept}`, outreach:`Hey ${candidate.name.split(" ")[0]},\n\nI’ve followed how you make ${candidate.niche.toLowerCase()} useful for working builders. I have a collaboration idea: “${candidate.concept}.”\n\nI’d bring the ${profile.niche.toLowerCase()} perspective, while you lead the build. The outcome would be one ${candidate.format.toLowerCase()} with practical takeaways for both audiences.\n\nOpen to a quick 20-minute outline next week?\n\n— ${profile.name}`, brief:["One focused technical story",`${candidate.format} as the hero asset`,"Each creator owns a distinct expert role","Short-form cutdowns for both audiences"], createdAt:new Date().toISOString() }; }
export function activity(kind:ActivityItem["kind"],title:string,detail:string):ActivityItem { return { id:makeId("activity"),kind,title,detail,at:time() }; }
export function candidateById(value:string){ return CANDIDATES.find(candidate=>candidate.id===value); }
